# Site settings
title: NATHAN EPSTEIN
tab: Nathan Epstein's Blog
email: nathan@wealthsimple.com
description:
   "This is a technical blog authored by Nathan Epstein."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: epstein_n
github_username:  NathanEpstein

# Build settings
markdown: kramdown
